name: Normal Scanner

on:
  schedule:
    - cron: "0 */4 * * *"   # runs every 4 hours
  workflow_dispatch:        # manual trigger

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install yfinance pandas requests

      - name: Run scanner
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TICKERS: ${{ secrets.TICKERS }}
        run: python normal_scanner.py
