name: Telegram Smoke Test

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram ping
        run: |
          set -e
          resp=$(curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ Telegram smoke test from GitHub Actions")
          echo "$resp"
          echo "$resp" | grep -q '"ok":true'
