name: NSE Swing Scanner

on:
  schedule:
    # Runs Mon–Fri at 17:30 IST (12:00 UTC)
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: heartbeat so you know the scan started
      - name: Telegram heartbeat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="⏱️ NSE scan started (GitHub Actions)." || true

      - name: Run scanner
        env:
          # Map your secrets to what config.py expects
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

          # Behavior
          SEND_EMPTY_REPORTS: "true"
          TIMEZONE: Asia/Kolkata
          INTERVAL: 1d
          PERIOD: 1y

          # Loosened strategy dials (tune later)
          VOL_MULT: "1.15"     # volume threshold vs 20d avg
          RSI_MIN: "45"        # momentum floor
          BO_LOOKBACK: "12"    # breakout over prior N-day high (prev days)
          ATR_STOP_MULT: "1.5"
          ATR_TRAIL_MULT: "3.0"

          # Turn on diagnostics only if needed
          DIAG_MODE: "false"
        run: |
          python scanner.py
