name: Swing Trading Bot

on:
  schedule:
    - cron: "0 9 * * 1-5"  # Run at 9 AM on weekdays (UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install yfinance matplotlib pandas

      - name: Run swing trading strategy
        run: python swing_trading_strategy.py
