name: Telegram Smoke Test

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Test getMe (valid token?)
        run: |
          set -e
          resp=$(curl -s "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getMe")
          echo "$resp"
          echo "$resp" | grep -q '"ok":true'
          echo "✅ getMe OK"

      - name: Send Telegram ping
        run: |
          set -e
          resp=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="✅ Telegram smoke test from GitHub Actions")
          echo "$resp"
          echo "$resp" | grep -q '"ok":true'
          echo "✅ sendMessage OK"
