name: NSE Swing Scanner

on:
  schedule:
    # Runs Mon–Fri at 17:30 IST (12:00 UTC)
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: one-line ping every run so you know it fired
      - name: Telegram heartbeat
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="⏱️ NSE scan started (GitHub Actions)."

      - name: Run scanner
        env:
          # Map your secrets to what the code expects
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

          # Behavior (safe defaults; adjust later)
          SEND_EMPTY_REPORTS: "true"
          TIMEZONE: Asia/Kolkata
          INTERVAL: 1d
          PERIOD: 1y

          # Strategy dials — relaxed a bit for testing
          VOL_MULT: "1.3"       # 1.5 is stricter
          RSI_MIN: "48"         # 50 is stricter
          BO_LOOKBACK: "18"     # 20 is stricter
          ATR_STOP_MULT: "1.5"
          ATR_TRAIL_MULT: "3.0"

          # Diagnostics: turn "true" for one run to see why symbols fail
          DIAG_MODE: "false"
        run: |
          python scanner.py
