name: NSE Swing Scanner

on:
  schedule:
    # 17:30 IST daily = 12:00 UTC (Mon–Fri)
    - cron: '0 12 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          # Optional tuning (can add as Secrets too)
          TIMEZONE: Asia/Kolkata
          INTERVAL: 1d
          PERIOD: 1y
          VOL_MULT: "1.5"
          RSI_MIN: "50"
          ATR_STOP_MULT: "1.5"
          ATR_TRAIL_MULT: "3.0"
          BO_LOOKBACK: "20"
          SEND_EMPTY_REPORTS: "true"
        run: |
          python scanner.py
